version: '3.7'
services:

  getface_db:
    container_name: getface-stage-db
    image: postgres:11
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=getface_stage
    volumes:
      - ./project/db:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - getface_stage_db_network

  getface_stage:
    build:
      context: ./
    container_name: getface-stage
    volumes:
      - ./:/var/www/get-face
    command: >
      bash -c "gunicorn app.wsgi -c /var/www/get-face/app/gunicorn.py --worker-class gevent --timeout 30 --graceful-timeout 20"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - getface_db
    networks:
      - getface_stage_network
      - getface_stage_db_network

  getface_nginx:
    image: nginx:1.15
    container_name: getface-stage-http
    volumes:
      - ./:/var/www/get-face
      - ./project/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/get-face
    ports:
      - 9090:9090
    links:
      - getface_stage
    depends_on:
      - getface_stage
    networks:
      - getface_stage_network

networks:
  getface_stage_network:
    driver: bridge
  getface_stage_db_network:
    driver: bridge
