version: '3.7'

services:

  getface_db:
    container_name: get-face-db
    domainname: get-face.com
    hostname: database
    image: postgres:11
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=get_face_stage
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - get_face
    restart: unless-stopped

  getface_stage:
    build:
      context: .
    image: getface_stage
    container_name: get-face-stage
    domainname: get-face.com
    hostname: stage
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DJANGO_ENVIRONMENT_MOD=dev
      - DJANGO_CONFIGURATION=Development
    volumes:
      - ./:/var/www/get-face
      - ./project/override/gunicorn:/usr/local/bin/gunicorn
      - ./project/override/pseudo_init.py:/usr/local/lib/python3.7/site-packages/gunicorn/workers/__init__.py
      - ./project/override/alternative.py:/usr/local/lib/python3.7/site-packages/gunicorn/workers/alternative.py
    command: >
      bash -c "gunicorn app.wsgi:get_face -c /var/www/get-face/app/gunicorn.py --timeout 30 --graceful-timeout 20"
    working_dir: /var/www/get-face
    ports:
      - 8091:8091
    networks:
      - get_face
    restart: unless-stopped

  getface_stage_watcher:
    build:
      context: ./project/assets
    container_name: get-face-stage-watcher
    ports:
      - 35729:35729
    depends_on:
      - getface_stage
    volumes:
      - ./:/var/www/get-face
    working_dir: /var/www/get-face/project/assets
    command: bash -c "npm i && npm run watch > ./../log/npm-watcher.log"
    restart: unless-stopped

  getface_nginx:
    image: nginx:1.15
    container_name: get-face-http
    domainname: get-face.com
    hostname: nginx
    volumes:
      - ./:/var/www/get-face
      - ./project/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/get-face
    ports:
      - 9090:9090
    networks:
      - get_face
    restart: unless-stopped

volumes:

  db:
    driver: local
    name: get-face-db

networks:
  get_face:
    name: get-face
    driver: bridge
