version: '3.7'
services:

  getface_db:
    container_name: getface-stage-db
    image: postgres:11
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=getface_stage
    volumes:
      - ./project/db/:/var/lib/postgresql/
    ports:
      - 5432:5432
    networks:
      - getface_stage_db_network

  getface_mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: get-face.com
    container_name: getface-mail
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./project/mail/main:/var/mail
      - ./project/mail/state:/var/mail-state
      - ./project/mail/config/:/tmp/docker-mailserver/
      - ./project/mail/mail-cert.crt:/etc/ssl/cert.pem
      - ./project/mail/mail-cert.key:/etc/ssl/cert.key
    networks:
      - getface_stage_network
      #- getface_prod_network
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - POSTMASTER_ADDRESS=admin@get-face.com
      - ONE_DIR=1
      - DMS_DEBUG=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/ssl/cert.pem
      - SSL_KEY_PATH=/etc/ssl/cert.key
    restart: always

  getface_stage:
    build:
      context: .
    container_name: getface-stage
    volumes:
      - ./:/var/www/get-face
      - ./project/override/gunicorn:/usr/local/bin/gunicorn
      - ./project/override/pseudo_init.py:/usr/local/lib/python3.7/site-packages/gunicorn/workers/__init__.py
      - ./project/override/alternative.py:/usr/local/lib/python3.7/site-packages/gunicorn/workers/alternative.py
    command: >
      bash -c "gunicorn index.wsgi:get_face -c /var/www/get-face/index/gunicorn.py --timeout 30 --graceful-timeout 20"
    working_dir: /var/www/get-face
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - getface_db
    networks:
      - getface_stage_network
      - getface_stage_db_network

  getface_nginx:
    image: nginx:1.15
    container_name: getface-stage-http
    volumes:
      - ./:/var/www/get-face
      - ./project/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/get-face
    ports:
      - 9090:9090
    links:
      - getface_stage
    networks:
      - getface_stage_network

networks:
  getface_stage_network:
    driver: bridge
  getface_stage_db_network:
    driver: bridge
