#!/usr/bin/env bash

c_error=`tput setaf 1`
c_success=`tput setaf 29`
c_clear=`tput sgr0`

git symbolic-ref --short HEAD 2> /dev/null

if [ $? -eq 0 ]; then
    git remote set-url origin git@bitbucket.org:GetFace/get-face.git
    git branch --set-upstream-to=origin/$(git symbolic-ref --short HEAD)
    echo "${c_success}>>> Git branch upstream set correctly.${c_clear}"
else
    echo "${c_error}>>> Head detached or some other problem. Set git branch manually.${c_clear}"
    tput bel
fi