#!/usr/bin/env bash
exec 2> /dev/null

for log in *.log; do
    {
        echo "" > ${log}
        echo "[$log] cleared"
    } || echo "File [$log] has not been cleared. Maybe you need more permissions?";
done
