# Generated by Django 2.1.4 on 2019-01-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('end', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_wanted', models.BooleanField(blank=True, default=None, null=True, verbose_name='Хочет работать')),
            ],
            options={
                'verbose_name': 'График работника',
                'verbose_name_plural': 'Графики работника',
            },
        ),
        migrations.CreateModel(
            name='WorkerFaceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('end', models.DateTimeField(verbose_name='Дата окончания')),
                ('active', models.IntegerField(default=0, verbose_name='Активность')),
                ('mood', models.IntegerField(default=0, verbose_name='Настроение')),
            ],
            options={
                'verbose_name': 'Показатель работника',
                'verbose_name_plural': 'Показатели работника',
            },
        ),
    ]
