# Generated by Django 2.1.5 on 2019-02-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('end', models.DateTimeField(verbose_name='Дата окончания')),
                ('active', models.SmallIntegerField(default=0, verbose_name='Активность')),
                ('mood', models.SmallIntegerField(default=0, verbose_name='Настроение')),
                ('fatigue', models.SmallIntegerField(default=0, verbose_name='Усталость')),
            ],
            options={
                'verbose_name': 'Показатель сотрудника',
                'verbose_name_plural': 'Показатели сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('end', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_wanted', models.NullBooleanField(default=None, verbose_name='Хочет работать')),
            ],
            options={
                'verbose_name': 'График сотрудника',
                'verbose_name_plural': 'Графики сотрудников',
            },
        ),
    ]
