# Generated by Django 2.1.4 on 2019-01-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerfacetime',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Worker', verbose_name='Работник'),
        ),
        migrations.AddField(
            model_name='workeragenda',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Worker', verbose_name='Работник'),
        ),
    ]
