# Generated by Django 2.1.3 on 2019-01-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeragenda',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Worker', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='workerfacetime',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Worker', verbose_name='Работник'),
        ),
    ]
