# Generated by Django 2.1.3 on 2019-01-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190117_1216'),
        ('agenda', '0002_auto_20190117_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAgenda',
        ),
        migrations.AlterModelOptions(
            name='workeragenda',
            options={'verbose_name': 'График работника', 'verbose_name_plural': 'Графики работника'},
        ),
        migrations.AddField(
            model_name='workeragenda',
            name='is_wanted',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Хочет работать'),
        ),
        migrations.AddField(
            model_name='workeragenda',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Работник', to='company.Worker'),
        ),
    ]
