# Generated by Django 2.1.4 on 2019-01-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190124_0803'),
        ('agenda', '0002_auto_20190121_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('end', models.DateTimeField(verbose_name='Дата окончания')),
                ('active', models.IntegerField(default=0, verbose_name='Активность')),
                ('mood', models.IntegerField(default=0, verbose_name='Настроение')),
                ('fatigue', models.IntegerField(default=0, verbose_name='Усталость')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Показатель работника',
                'verbose_name_plural': 'Показатели работника',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('end', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_wanted', models.NullBooleanField(default=None, verbose_name='Хочет работать')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'График работника',
                'verbose_name_plural': 'Графики работника',
            },
        ),
        migrations.RemoveField(
            model_name='workeragenda',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workerfacetime',
            name='worker',
        ),
        migrations.DeleteModel(
            name='WorkerAgenda',
        ),
        migrations.DeleteModel(
            name='WorkerFaceTime',
        ),
    ]
