# Generated by Django 2.1.3 on 2019-01-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20190117_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerFaceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('end', models.DateTimeField(verbose_name='Дата окончания')),
                ('activeness', models.IntegerField(default=0, max_length=3, verbose_name='Активность')),
                ('mood', models.IntegerField(default=0, max_length=3, verbose_name='Настроение')),
            ],
            options={
                'verbose_name': 'Показатель работника',
                'verbose_name_plural': 'Показатели работника',
            },
        ),
    ]
