# Generated by Django 2.1.3 on 2019-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_workerfacetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerfacetime',
            name='activeness',
            field=models.IntegerField(default=0, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='workerfacetime',
            name='mood',
            field=models.IntegerField(default=0, verbose_name='Настроение'),
        ),
    ]
