# Generated by Django 2.1.5 on 2019-02-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('agenda', '0004_auto_20190128_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='worker',
        ),
        migrations.AddField(
            model_name='agenda',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Работник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Работник'),
            preserve_default=False,
        ),
    ]
