# Generated by Django 2.1.3 on 2019-01-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190117_1216'),
        ('agenda', '0005_auto_20190117_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerfacetime',
            old_name='activeness',
            new_name='active',
        ),
        migrations.AddField(
            model_name='workerfacetime',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Worker', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='workeragenda',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Worker', verbose_name='Работник'),
        ),
    ]
