# Generated by Django 2.1.5 on 2019-02-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20190206_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Показатель сотрудника', 'verbose_name_plural': 'Показатели сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'График сотрудника', 'verbose_name_plural': 'Графики сотрудников'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Сотрудник'),
        ),
    ]
