# Generated by Django 2.1.7 on 2019-04-11 16:11

import common.models.image.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190411_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=common.models.image.model.Image.computed_folder, verbose_name='Изображение'),
        ),
    ]
