# Generated by Django 2.1.7 on 2019-04-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190411_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Оригинальное имя'),
        ),
    ]
