# Generated by Django 2.2 on 2019-04-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0005_auto_20190411_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='holding.Company', verbose_name='Компания')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to='holding.Employee', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Основатель',
                'verbose_name_plural': 'Основатели',
            },
        ),
    ]
