# Generated by Django 2.2 on 2019-04-17 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holding', '0007_auto_20190417_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycreator',
            name='physical',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Физический пользователь'),
        ),
        migrations.AlterField(
            model_name='companycreator',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='holding.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companycreator',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creators', to='holding.Employee', verbose_name='Создатель'),
        ),
    ]
