# Generated by Django 2.2 on 2019-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0009_auto_20190421_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_protected',
            field=models.BooleanField(default=False, verbose_name='Неудаляемый отдел'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_protected',
            field=models.BooleanField(default=False, verbose_name='Неудаляемая должность'),
        ),
    ]
