# Generated by Django 2.2 on 2019-04-21 20:37

import app.fields.timezone.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0010_auto_20190421_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiontodepartment',
            options={'verbose_name': 'Должность к отделу', 'verbose_name_plural': 'Должности к отделам'},
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='holding.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='timezone',
            field=app.fields.timezone.fields.TimeZoneField(blank=True, default='UTC', verbose_name='Пояс'),
        ),
        migrations.AlterField(
            model_name='positiontodepartment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='holding.Position'),
        ),
    ]
