from wtforms import (
    Field,
    FieldList as List,
    PasswordField as Password,
    FileField as File,
    StringField as String,
    TextField as Text,
    BooleanField as Boolean,
    FloatField as Float,
    IntegerField as Integer,
    DateTimeField as DateTime,
    HiddenField as Field,
    DateField as Date,
    DecimalField as Decimal,
    MultipleFileField as MultipleFile,
    RadioField as Radio,
    SelectField as Select,
    SelectMultipleField as SelectMultiple,
    TextAreaField as TextArea,
    TimeField as Time,
)
