# Generated by Django 2.1.5 on 2019-03-14 11:31

from django.db import migrations, models
import index.fields.timezone.fields


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=index.fields.timezone.fields.TimeZoneField(blank=True, default='UTC', verbose_name='Локальное время пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated'),
        ),
    ]
