# Generated by Django 2.1.5 on 2019-02-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation',
            field=models.CharField(default='a5d631e28995eca4ca7c8a8c89f654db', editable=False, max_length=255, verbose_name='Код активации'),
        ),
    ]
