# Generated by Django 2.1.3 on 2019-01-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_feature_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
