# Generated by Django 2.1.5 on 2019-02-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20190206_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation',
            field=models.CharField(default='c9639501ebdd6e2c17a7ed16053ce055', editable=False, max_length=255, null=True, verbose_name='Код активации/восстановления пароля'),
        ),
    ]
