# Generated by Django 2.1.5 on 2019-02-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20190206_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation',
            field=models.CharField(default='95531aac97f9434443728355e8c91e3e', editable=False, max_length=255, null=True, verbose_name='Код активации/восстановления пароля'),
        ),
    ]
