# Generated by Django 2.1.5 on 2019-02-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20190206_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation',
            field=models.CharField(default='e755a2930c3fdff43b0c157e35193e3b', editable=False, max_length=255, null=True, verbose_name='Код активации/восстановления пароля'),
        ),
    ]
