# Generated by Django 2.1.5 on 2019-02-06 19:39

import authentication.models.user.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20190206_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation',
            field=models.CharField(default=authentication.models.user.model._activation_key, editable=False, max_length=255, null=True, verbose_name='Код активации/восстановления пароля'),
        ),
    ]
