# Generated by Django 2.1.4 on 2019-01-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название скидки')),
                ('percent', models.SmallIntegerField(default=0, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
