# Generated by Django 2.1.5 on 2019-03-14 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(default=datetime.datetime(2019, 3, 14, 11, 31, 21, 717964), verbose_name='Дата начала действия тарифа')),
                ('discount_percent', models.FloatField(blank=True, default=None, null=True, verbose_name='Процент скидки на момент платежа')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('discount', models.ForeignKey(null=True, on_delete=models.SET(None), to='company.Discount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rate',
        ),
        migrations.AddField(
            model_name='rate',
            name='lifetime',
            field=models.DurationField(default=datetime.timedelta(days=30), verbose_name='Время действия тарифа'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='per_month',
            field=models.FloatField(verbose_name='Цена за месяц'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.Payment'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Rate', verbose_name='Выбранный тариф'),
        ),
    ]
