# Generated by Django 2.1.3 on 2019-01-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='E-mail'),
        ),
    ]
