# Generated by Django 2.1.4 on 2019-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190128_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='company.Discount'),
        ),
    ]
