# Generated by Django 2.1.5 on 2019-03-14 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190314_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата начала действия тарифа'),
        ),
    ]
