# Generated by Django 2.1.4 on 2019-01-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_payment_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.Payment'),
        ),
        migrations.AddField(
            model_name='company',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.Rate'),
        ),
    ]
