# Generated by Django 2.1.3 on 2019-01-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190114_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Компания'),
        ),
    ]
