# Generated by Django 2.1.5 on 2019-03-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190314_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Discount'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Почтовый ящик'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Discount'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Discount'),
        ),
    ]
