# Generated by Django 2.1.3 on 2019-01-17 11:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_auto_20190116_0858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('user', 'company')},
        ),
    ]
