# Generated by Django 2.1.5 on 2019-03-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0005_auto_20190314_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name': 'Дополнительные детали', 'verbose_name_plural': 'Детали оплат'},
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='company.PaymentDetails', verbose_name='Детали'),
            preserve_default=False,
        ),
    ]
