# Generated by Django 2.1.4 on 2019-01-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190128_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='payment',
        ),
        migrations.AddField(
            model_name='company',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='company.Discount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.Company', verbose_name='Компания'),
        ),
    ]
