# Generated by Django 2.1.3 on 2019-01-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190108_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес компании'),
        ),
    ]
