# Generated by Django 2.1.5 on 2019-02-05 16:53

from django.db import migrations
import index.fields.timezone.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190128_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=index.fields.timezone.fields.TimeZoneField(blank=True, default='UTC', verbose_name='Локальное время компании'),
        ),
    ]
