# Generated by Django 2.1.3 on 2019-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190117_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated'),
        ),
    ]
