# Generated by Django 2.1.3 on 2019-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190109_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание компании'),
        ),
    ]
