# Generated by Django 2.1.5 on 2019-03-22 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0006_auto_20190314_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='rate',
        ),
    ]
