# Generated by Django 2.1.7 on 2019-04-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_company_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='company.PaymentDetails', verbose_name='Детали'),
        ),
    ]
