# Generated by Django 2.1.3 on 2019-01-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Описание компании'),
        ),
    ]
