# Generated by Django 2.1.5 on 2019-02-05 16:57

from django.db import migrations, models
import index.fields.timezone.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='timezone',
            field=index.fields.timezone.fields.TimeZoneField(blank=True, default='UTC', verbose_name='Локальное время работника'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
