# Generated by Django 2.1.5 on 2019-02-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190205_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела/цеха')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='WorkerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название должности')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='face_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Face ID'),
        ),
        migrations.AddField(
            model_name='worker',
            name='invitation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее приглашение'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='Приглашён'),
        ),
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='company.WorkerDepartment'),
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='company.WorkerPosition'),
        ),
    ]
