# Generated by Django 2.1.3 on 2019-01-09 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190109_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='auth_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный авторизационный ключ'),
        ),
    ]
