# Generated by Django 2.1.3 on 2019-01-10 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_worker_auth_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date post created'),
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date post updated'),
        ),
        migrations.AddField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date post created'),
        ),
        migrations.AddField(
            model_name='worker',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date post updated'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='auth_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Уникальный авторизационный ключ'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон'),
        ),
    ]
