# Generated by Django 2.1.5 on 2019-02-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20190206_1927'),
        ('company', '0009_auto_20190206_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='company',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='department',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workerdepartment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workerposition',
            name='company',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='WorkerDepartment',
        ),
        migrations.DeleteModel(
            name='WorkerPosition',
        ),
    ]
