# Generated by Django 2.1.7 on 2019-04-11 10:02

import app.fields.timezone.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Начало отрезка')),
                ('end', models.DateTimeField(verbose_name='Конец отрезка')),
                ('activity', models.PositiveSmallIntegerField(default=0, verbose_name='Активность')),
                ('mood', models.PositiveSmallIntegerField(default=0, verbose_name='Настроение')),
                ('fatigue', models.PositiveSmallIntegerField(default=0, verbose_name='Усталость')),
                ('timezone', app.fields.timezone.fields.TimeZoneField(blank=True, null=True, verbose_name='Временная зона')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbooks', to='holding.Employee')),
            ],
            options={
                'verbose_name': 'Показатель сотрудника',
                'verbose_name_plural': 'Показатели сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('is_wanted', models.NullBooleanField(default=None, verbose_name='Хочет работать')),
                ('timezone', app.fields.timezone.fields.TimeZoneField(blank=True, null=True, verbose_name='Временная зона')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='holding.Employee')),
            ],
            options={
                'verbose_name': 'График сотрудника',
                'verbose_name_plural': 'Графики сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('when', models.DateTimeField(verbose_name='Когда')),
                ('title', models.CharField(max_length=128, verbose_name='Название нарушения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание нарушения')),
                ('timezone', app.fields.timezone.fields.TimeZoneField(blank=True, null=True, verbose_name='Временная зона')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='holding.Employee')),
            ],
            options={
                'verbose_name': 'Нарушение',
                'verbose_name_plural': 'Нарушения',
            },
        ),
    ]
