# Generated by Django 2.1.7 on 2019-04-11 12:44

import app.fields.timezone.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holding', '0005_auto_20190411_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('login', models.CharField(max_length=256, verbose_name='Логин')),
                ('password', models.CharField(blank=True, default='', max_length=256, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('timezone', app.fields.timezone.fields.TimeZoneField(blank=True, null=True, verbose_name='Временная зона')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='holding.Company')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('face_id', models.CharField(max_length=64, verbose_name='Face ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holding.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('filename', models.CharField(max_length=128, verbose_name='Название файла')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.Camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date record created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date record updated')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='holding.Company')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cam.Zone'),
        ),
    ]
