# Generated by Django 2.1.7 on 2019-04-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='face',
            options={'verbose_name': 'Лицо', 'verbose_name_plural': 'Лица'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
